# Generated by Django 2.2.4 on 2019-10-15 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enhydris", "0025_gentity_geom"),
        ("enhydris_openhigis", "0002_remove_water_district_length_and_area"),
    ]

    operations = [
        migrations.RenameModel(old_name="WaterDistrict", new_name="RiverBasinDistrict"),
        migrations.RunSQL(
            """
            DROP TRIGGER IF EXISTS water_districts_insert
                ON openhigis.water_districts;
            DROP TRIGGER IF EXISTS water_districts_update
                ON openhigis.water_districts;
            DROP TRIGGER IF EXISTS water_districts_delete
                ON openhigis.water_districts;
            DROP VIEW IF EXISTS openhigis.water_districts;
            DROP FUNCTION IF EXISTS openhigis.insert_into_water_districts();
            DROP FUNCTION IF EXISTS openhigis.update_water_districts();
            DROP FUNCTION IF EXISTS openhigis.delete_water_districts();
            """
        ),
    ]
