# Generated by Django 2.2.4 on 2019-10-22 12:37

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.contrib.gis.geos import Point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enhydris", "0025_gentity_geom"),
        ("enhydris_openhigis", "0003_rename_water_district_to_river_basin_district"),
    ]

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "station_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="enhydris.Station",
                    ),
                ),
                (
                    "geom2100",
                    django.contrib.gis.db.models.fields.GeometryField(srid=2100),
                ),
            ],
            options={"abstract": False},
            bases=("enhydris.station", models.Model),
        ),
        migrations.AddField(
            model_name="riverbasindistrict",
            name="geom2100",
            field=django.contrib.gis.db.models.fields.GeometryField(
                default=Point(x=0, y=0, srid=2100), srid=2100
            ),
            preserve_default=False,
        ),
        migrations.RunSQL(
            "INSERT INTO enhydris_openhigis_station(station_ptr_id, geom2100) "
            "SELECT gpoint_ptr_id, ST_Transform(g.geom, 2100) "
            "FROM enhydris_station s, enhydris_gentity g WHERE g.id=s.gpoint_ptr_id;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            "UPDATE enhydris_openhigis_riverbasindistrict d "
            "SET geom2100=ST_Transform(geom, 2100) "
            "FROM enhydris_gentity g WHERE g.id = d.garea_ptr_id;",
            reverse_sql="",
        ),
    ]
