# Generated by Django 2.2.4 on 2019-10-30 10:23

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enhydris", "0025_gentity_geom"),
        ("enhydris_openhigis", "0005_riverbasin"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrainageBasin",
            fields=[
                (
                    "garea_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="enhydris.Garea",
                    ),
                ),
                (
                    "geom2100",
                    django.contrib.gis.db.models.fields.GeometryField(srid=2100),
                ),
                ("hydro_order", models.CharField(blank=True, max_length=50)),
                ("hydro_order_scheme", models.CharField(blank=True, max_length=50)),
                ("hydro_order_scope", models.CharField(blank=True, max_length=50)),
                ("man_made", models.BooleanField(blank=True, null=True)),
                ("total_area", models.FloatField(blank=True, null=True)),
                ("mean_slope", models.FloatField(blank=True, null=True)),
                ("mean_elevation", models.FloatField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="self",
                    ),
                ),
            ],
            options={"abstract": False},
            bases=("enhydris.garea", models.Model),
        ),
        migrations.DeleteModel(name="RiverBasin"),
        migrations.CreateModel(
            name="RiverBasin",
            fields=[
                (
                    "drainagebasin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="enhydris_openhigis.DrainageBasin",
                    ),
                )
            ],
            options={"abstract": False},
            bases=("enhydris_openhigis.drainagebasin",),
        ),
    ]
