# Generated by Django 2.2.7 on 2019-11-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("enhydris_openhigis", "0009_drainagebasin_riverbasin")]

    operations = [
        migrations.RemoveField(model_name="riverbasin", name="hydro_order"),
        migrations.RemoveField(model_name="riverbasin", name="hydro_order_scheme"),
        migrations.RemoveField(model_name="riverbasin", name="hydro_order_scope"),
        migrations.RemoveField(model_name="riverbasin", name="total_area"),
    ]
