# Generated by Django 2.2.7 on 2020-03-05 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enhydris_openhigis", "0017_hydronode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stationbasin",
            name="station",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="enhydris_openhigis.Station",
            ),
        ),
    ]
