# Generated by Django 2.2.19 on 2021-02-26 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enhydris_openhigis", "0102_watercourse_changes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drainagebasin",
            name="hydro_order",
        ),
        migrations.RemoveField(
            model_name="drainagebasin",
            name="hydro_order_scheme",
        ),
        migrations.RemoveField(
            model_name="drainagebasin",
            name="hydro_order_scope",
        ),
        migrations.AddField(
            model_name="basin",
            name="area",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="basin",
            name="concentration_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="basin",
            name="hydro_order",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="basin",
            name="hydro_order_scheme",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="basin",
            name="hydro_order_scope",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="basin",
            name="mean_cn",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="basin",
            name="outlet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="enhydris_openhigis.HydroNode",
            ),
        ),
        migrations.AddField(
            model_name="basin",
            name="outlet_elevation",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="basin",
            name="watercourse_main_length",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="basin",
            name="watercourse_main_slope",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stationbasin",
            name="area",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stationbasin",
            name="concentration_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stationbasin",
            name="hydro_order",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="stationbasin",
            name="hydro_order_scheme",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="stationbasin",
            name="hydro_order_scope",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="stationbasin",
            name="mean_cn",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stationbasin",
            name="outlet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="enhydris_openhigis.HydroNode",
            ),
        ),
        migrations.AddField(
            model_name="stationbasin",
            name="outlet_elevation",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stationbasin",
            name="watercourse_main_length",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stationbasin",
            name="watercourse_main_slope",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
