# Generated by Django 2.2.19 on 2021-03-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enhydris_openhigis", "0103_basin_changes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basin",
            name="max_river_length",
        ),
        migrations.RemoveField(
            model_name="stationbasin",
            name="max_river_length",
        ),
    ]
