# Generated by Django 2.2.19 on 2021-03-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enhydris_openhigis", "0105_standing_water"),
    ]

    operations = [
        migrations.AddField(
            model_name="hydronode",
            name="hydro_node_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("boundary", "boundary"),
                    ("flowConstriction", "flowConstriction"),
                    ("flowRegulation", "flowRegulation"),
                    ("junction", "junction"),
                    ("outlet", "outlet"),
                    ("source", "source"),
                ],
                max_length=16,
            ),
        ),
    ]
