# Generated by Django 3.2.2 on 2021-08-20 11:00

import django.contrib.sites.managers
import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enhydris_openhigis", "0107_remove_station_geom2100"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="station",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
